services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=whizzly
      - DB_PASSWORD=kelompok7
      - DB_NAME=whizzly_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=kelompok7
      - RACK_ENV=production
      - THREAD_POOL_SIZE=10
      - THREAD_POOL_QUEUE=100
      - WEB_CONCURRENCY=2
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - FACEBOOK_CLIENT_ID=your_facebook_client_id
      - FACEBOOK_CLIENT_SECRET=your_facebook_client_secret
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    restart: unless-stopped
    networks:
      - my_network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=whizzly_db
      - MYSQL_USER=whizzly
      - MYSQL_PASSWORD=kelompok7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306" 
    command: >
      --default-authentication-plugin=mysql_native_password  
      --bind-address=0.0.0.0
      --host_cache_size=0
      --tls-version=  
      --pid-file=/var/lib/mysql/mysql.pid
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "whizzly", "-pkelompok7"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - my_network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  my_network :
    driver: bridge